### ISSUE TITLE
Issue in converting .sam to .bam

### ISSUE THREAD

**Issue by spencer411** [bhattlab/MGEfinder#23]
When I attempt to convert .sam to .bam I get the following error and no .bam file is created:

(mgefinder) -bash-4.2$ mgefinder formatbam 1027D_19.NC_014925.1.sam 1027D_19.NC_014925.1.bam
Traceback (most recent call last):
  File "/network/rit/lab/andamlab/bin/miniconda3/envs/mgefinder/bin/mgefinder", line 7, in <module>
    from mgefinder.main import cli
  File "/network/rit/lab/andamlab/bin/miniconda3/envs/mgefinder/lib/python3.7/site-packages/mgefinder/main.py", line 6, in <module>
    from mgefinder.pair import _pair
  File "/network/rit/lab/andamlab/bin/miniconda3/envs/mgefinder/lib/python3.7/site-packages/mgefinder/pair.py", line 8, in <module>
    from mgefinder import fastatools, embosstools, pysamtools, sctools
  File "/network/rit/lab/andamlab/bin/miniconda3/envs/mgefinder/lib/python3.7/site-packages/mgefinder/fastatools.py", line 6, in <module>
    from Bio.Alphabet import IUPAC
  File "/network/rit/lab/andamlab/bin/miniconda3/envs/mgefinder/lib/python3.7/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

**Comment by spencer411** [comment]
Nevermind, fixed with a reinstall.
