### ISSUE TITLE
Error in pair step

### ISSUE THREAD

**Issue by erinpnewcomer** [bhattlab/MGEfinder#35]
Hi! I'm running into an error on the pair step while using MGEfinder v1.0.6. I'm using the workflow denovo command, and the working directory only produces the 01.mgefinder directory. Within the ~/01.mgefinder/<ref>/<sample>/log/<sample>.<ref>.pair.log.err file, I get this error:

Traceback (most recent call last):
  File "/home/erin.newcomer/.conda/envs/mgefinder/bin/mgefinder", line 8, in <module>
    sys.exit(cli())
  File "/home/erin.newcomer/.conda/envs/mgefinder/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/erin.newcomer/.conda/envs/mgefinder/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/erin.newcomer/.conda/envs/mgefinder/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erin.newcomer/.conda/envs/mgefinder/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/erin.newcomer/.conda/envs/mgefinder/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/erin.newcomer/.conda/envs/mgefinder/lib/python3.6/site-packages/mgefinder/main.py", line 194, in pair
    min_alignment_inner_length, max_junction_spanning_prop, large_insertion_cutoff, output_file)
  File "/home/erin.newcomer/.conda/envs/mgefinder/lib/python3.6/site-packages/mgefinder/pair.py", line 40, in _pair
    flank_pairs = flank_pairer.run_pair_flanks()
  File "/home/erin.newcomer/.conda/envs/mgefinder/lib/python3.6/site-packages/mgefinder/pair.py", line 113, in run_pair_flanks
    final_pairs = self.get_direct_repeats(filtered_pairs)
  File "/home/erin.newcomer/.conda/envs/mgefinder/lib/python3.6/site-packages/mgefinder/pair.py", line 278, in get_direct_repeats
    positions = self.get_reference_direct_repeats(flank_pairs, genome_dict)
  File "/home/erin.newcomer/.conda/envs/mgefinder/lib/python3.6/site-packages/mgefinder/pair.py", line 292, in get_reference_direct_repeats
    direct_repeat = genome_dict[contig][(start+1):end]
KeyError: '1'

Do you have any advice?

**Comment by durrantmm** [comment]
Ok, this looks like a problem with the way the contigs are named in the reference genome. Sorry, an annoying error. You can either try renaming the contigs, or you can share the genome with me and I can try to fix the problem.

**Comment by erinpnewcomer** [comment]
No worries! I saw an earlier error that had an issue if the contigs were only named with an integer (mine were). I tried lazily by concatenating the length and depth info on, so the names now look like '>18length=125depth=1.68x' and it still has this issue. Would naming them something simple like 'contig1' likely fix this?

**Comment by durrantmm** [comment]
Yes it probably would. It's dumb I know, sorry!

**Comment by erinpnewcomer** [comment]
I tried running it again with the updated reference genome contig name, and I'm still encountering the same error. Any suggestions?

**Comment by erinpnewcomer** [comment]
I re-aligned everything and ran it again, and it worked this time! Thank you so much!
