### ISSUE TITLE
error in step mgefinder formatbam

### ISSUE THREAD

**Issue by Oelsakha** [bhattlab/MGEfinder#41]
**Hi all 
please, if anyone can help me 
I am trying to run this code** 
(mgefinder) lololly-MBP MGEfinder % mgefinder formatbam s5.sam s5.bam    
**but gave me this error**                         
#### CHECKING DEPENDENCIES ####
Current version of snakemake: 3.13.3
Expected version of snakemake: 3.13.3
Current version of einverted: EMBOSS:6.6.0.0
Expected version of einverted: EMBOSS:6.6.0.0
Traceback (most recent call last):
  File "/Users/lololly/miniconda3/envs/mgefinder/bin/mgefinder", line 5, in <module>
    from mgefinder.main import cli
  File "/Users/lololly/miniconda3/envs/mgefinder/lib/python3.6/site-packages/mgefinder/main.py", line 38, in <module>
    check_dependencies()
  File "/Users/lololly/miniconda3/envs/mgefinder/lib/python3.6/site-packages/mgefinder/dependencies.py", line 39, in check_dependencies
    bowtie2_checker.check(extract_version=lambda x: x.split()[2])
  File "/Users/lololly/miniconda3/envs/mgefinder/lib/python3.6/site-packages/mgefinder/dependencies.py", line 12, in check
    output = shell(cmd.format(tool=self.tool), read=True).decode('utf-8').strip()
  File "/Users/lololly/miniconda3/envs/mgefinder/lib/python3.6/site-packages/snakemake/shell.py", line 88, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bowtie2 --version 2>&1' returned non-zero exit status 255.

**Comment by Oelsakha** [comment]
never mind, it solved

**Comment by durrantmm** [comment]
Great!
